-- Enable pgcrypto for UUID generation if not enabled
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Societies
CREATE TABLE societies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Towers
CREATE TABLE towers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  society_id UUID REFERENCES societies(id) ON DELETE CASCADE,
  name TEXT NOT NULL, -- e.g., "Tower A"
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Flats
CREATE TABLE flats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tower_id UUID REFERENCES towers(id) ON DELETE CASCADE,
  number TEXT NOT NULL, -- e.g., "402"
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Profiles (Linked to auth.users eventually, but can exist as invited first)
CREATE TYPE user_role AS ENUM ('resident', 'guard', 'admin');

CREATE TABLE profiles (
  id UUID PRIMARY KEY, -- matches auth.users.id
  society_id UUID REFERENCES societies(id) ON DELETE CASCADE,
  role user_role NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  avatar_url TEXT,
  flat_id UUID REFERENCES flats(id) ON DELETE SET NULL, -- Null for guards/admins
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4.5. Invites (Pre-created by Admin before user signs up)
CREATE TABLE invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  society_id UUID REFERENCES societies(id) ON DELETE CASCADE,
  role user_role NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  flat_id UUID REFERENCES flats(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Function to handle new auth users and claim their invite
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  invite_record RECORD;
BEGIN
  -- Look for an invite matching the phone number
  SELECT * INTO invite_record FROM public.invites WHERE phone = NEW.phone LIMIT 1;
  
  IF FOUND THEN
    -- Insert into profiles using the auth.users.id
    INSERT INTO public.profiles (id, society_id, role, full_name, phone, flat_id)
    VALUES (NEW.id, invite_record.society_id, invite_record.role, invite_record.full_name, invite_record.phone, invite_record.flat_id);
    
    -- Delete the invite now that it's claimed
    DELETE FROM public.invites WHERE id = invite_record.id;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger on auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. Visitors (Master record of a person)
CREATE TABLE visitors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  phone TEXT,
  photo_url TEXT,
  id_proof_url TEXT,
  category TEXT NOT NULL, -- delivery, cab, guest, service
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Visitor Requests (Transaction log for approval loop)
CREATE TYPE request_status AS ENUM ('pending', 'approved', 'rejected', 'expired');

CREATE TABLE visitor_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  visitor_id UUID REFERENCES visitors(id) ON DELETE CASCADE,
  flat_id UUID REFERENCES flats(id) ON DELETE CASCADE,
  created_by UUID REFERENCES profiles(id), -- The guard
  status request_status DEFAULT 'pending',
  decided_by UUID REFERENCES profiles(id), -- The resident
  decided_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Guest Pre-approvals (Generated by resident)
CREATE TYPE preapproval_status AS ENUM ('active', 'used', 'expired', 'revoked');

CREATE TABLE guest_preapprovals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  flat_id UUID REFERENCES flats(id) ON DELETE CASCADE,
  resident_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  guest_name TEXT NOT NULL,
  valid_from TIMESTAMPTZ NOT NULL,
  valid_until TIMESTAMPTZ NOT NULL,
  qr_token TEXT UNIQUE NOT NULL,
  status preapproval_status DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Entry / Exit Logs
CREATE TYPE ref_type_enum AS ENUM ('request', 'preapproval', 'staff');

CREATE TABLE entry_exit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ref_type ref_type_enum NOT NULL,
  ref_id UUID NOT NULL, -- ID of visitor_request or guest_preapproval
  guard_id UUID REFERENCES profiles(id),
  entry_time TIMESTAMPTZ DEFAULT NOW(),
  exit_time TIMESTAMPTZ
);

-- 9. Complaints
CREATE TYPE complaint_status AS ENUM ('open', 'in_progress', 'resolved', 'closed');

CREATE TABLE complaints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  flat_id UUID REFERENCES flats(id) ON DELETE CASCADE,
  resident_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  photo_url TEXT,
  status complaint_status DEFAULT 'open',
  assigned_to UUID REFERENCES profiles(id), -- Admin assigned
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Notices
CREATE TABLE notices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  society_id UUID REFERENCES societies(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  image_url TEXT,
  pinned BOOLEAN DEFAULT FALSE,
  created_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Polls & Votes
CREATE TABLE polls (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  society_id UUID REFERENCES societies(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  closes_at TIMESTAMPTZ,
  created_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE poll_options (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  poll_id UUID REFERENCES polls(id) ON DELETE CASCADE,
  label TEXT NOT NULL
);

CREATE TABLE poll_votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  poll_id UUID REFERENCES polls(id) ON DELETE CASCADE,
  option_id UUID REFERENCES poll_options(id) ON DELETE CASCADE,
  resident_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(poll_id, resident_id) -- Enforces one vote per resident per poll
);

-- 12. Amenities & Bookings
CREATE TABLE amenities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  society_id UUID REFERENCES societies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  capacity INT NOT NULL,
  open_time TIME,
  close_time TIME,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TYPE booking_status AS ENUM ('confirmed', 'cancelled');

CREATE TABLE amenity_bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  amenity_id UUID REFERENCES amenities(id) ON DELETE CASCADE,
  flat_id UUID REFERENCES flats(id) ON DELETE CASCADE,
  resident_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  status booking_status DEFAULT 'confirmed',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Staff Directory
CREATE TABLE staff_directory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  society_id UUID REFERENCES societies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  phone TEXT,
  photo_url TEXT,
  verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =================================================================================
-- ROW LEVEL SECURITY (RLS)
-- =================================================================================

-- Turn on RLS for all tables
ALTER TABLE societies ENABLE ROW LEVEL SECURITY;
ALTER TABLE towers ENABLE ROW LEVEL SECURITY;
ALTER TABLE flats ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitor_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE guest_preapprovals ENABLE ROW LEVEL SECURITY;
ALTER TABLE entry_exit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE amenity_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_directory ENABLE ROW LEVEL SECURITY;

-- Helper function to get current user's profile
CREATE OR REPLACE FUNCTION public.user_profile() RETURNS profiles AS $$
  SELECT * FROM profiles WHERE id = auth.uid() LIMIT 1;
$$ LANGUAGE sql STABLE;

-- Societies: Everyone can read their own society
CREATE POLICY "Users can view their society" ON societies FOR SELECT
  USING (id = (public.user_profile()).society_id);

-- Towers & Flats: Everyone in society can view
CREATE POLICY "Users can view towers in their society" ON towers FOR SELECT
  USING (society_id = (public.user_profile()).society_id);
CREATE POLICY "Users can view flats in their society" ON flats FOR SELECT
  USING (tower_id IN (SELECT id FROM towers WHERE society_id = (public.user_profile()).society_id));

-- Profiles: Users can view profiles in their society
CREATE POLICY "Users can view profiles in their society" ON profiles FOR SELECT
  USING (society_id = (public.user_profile()).society_id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE
  USING (id = auth.uid());

-- Invites: Admins can manage, Guards can't, Residents can't.
CREATE POLICY "Admins can manage invites" ON invites FOR ALL
  USING ((public.user_profile()).role = 'admin');

-- Visitor Requests
CREATE POLICY "Guards and Admins can view all requests in society" ON visitor_requests FOR SELECT
  USING ((public.user_profile()).role IN ('guard', 'admin'));
CREATE POLICY "Residents can view requests for their flat" ON visitor_requests FOR SELECT
  USING (flat_id = (public.user_profile()).flat_id);
CREATE POLICY "Guards can create visitor requests" ON visitor_requests FOR INSERT
  WITH CHECK ((public.user_profile()).role = 'guard');
CREATE POLICY "Residents can update requests for their flat (approve/reject)" ON visitor_requests FOR UPDATE
  USING (flat_id = (public.user_profile()).flat_id);

-- Guest Preapprovals
CREATE POLICY "Guards and Admins can view all preapprovals" ON guest_preapprovals FOR SELECT
  USING ((public.user_profile()).role IN ('guard', 'admin'));
CREATE POLICY "Residents can view and create preapprovals for their flat" ON guest_preapprovals FOR ALL
  USING (flat_id = (public.user_profile()).flat_id);

-- Entry/Exit Logs
CREATE POLICY "Guards and Admins can manage all logs" ON entry_exit_logs FOR ALL
  USING ((public.user_profile()).role IN ('guard', 'admin'));
-- Residents can view logs linked to their flat's requests or preapprovals (simplified here for brevity, typically requires join)

-- Complaints
CREATE POLICY "Admins can view and manage all complaints" ON complaints FOR ALL
  USING ((public.user_profile()).role = 'admin');
CREATE POLICY "Residents can view and manage their own complaints" ON complaints FOR ALL
  USING (resident_id = auth.uid());

-- Notices
CREATE POLICY "Everyone can view notices" ON notices FOR SELECT
  USING (society_id = (public.user_profile()).society_id);
CREATE POLICY "Admins can manage notices" ON notices FOR ALL
  USING ((public.user_profile()).role = 'admin');

-- Polls
CREATE POLICY "Everyone can view polls" ON polls FOR SELECT
  USING (society_id = (public.user_profile()).society_id);
CREATE POLICY "Admins can manage polls" ON polls FOR ALL
  USING ((public.user_profile()).role = 'admin');

CREATE POLICY "Everyone can view poll options" ON poll_options FOR SELECT
  USING (true);
CREATE POLICY "Everyone can view poll votes" ON poll_votes FOR SELECT
  USING (true);
CREATE POLICY "Residents can vote" ON poll_votes FOR INSERT
  WITH CHECK (resident_id = auth.uid());

-- Amenities & Bookings
CREATE POLICY "Everyone can view amenities" ON amenities FOR SELECT
  USING (society_id = (public.user_profile()).society_id);
CREATE POLICY "Admins can manage amenities" ON amenities FOR ALL
  USING ((public.user_profile()).role = 'admin');

CREATE POLICY "Everyone can view bookings" ON amenity_bookings FOR SELECT
  USING (true);
CREATE POLICY "Residents can manage their own bookings" ON amenity_bookings FOR ALL
  USING (resident_id = auth.uid());

-- Staff Directory
CREATE POLICY "Everyone can view staff directory" ON staff_directory FOR SELECT
  USING (society_id = (public.user_profile()).society_id);
CREATE POLICY "Admins can manage staff directory" ON staff_directory FOR ALL
  USING ((public.user_profile()).role = 'admin');


-- =================================================================================
-- STORAGE BUCKETS (Note: Needs to be run via Supabase dashboard / API)
-- =================================================================================
-- INSERT INTO storage.buckets (id, name, public) VALUES ('visitor-photos', 'visitor-photos', true);
-- INSERT INTO storage.buckets (id, name, public) VALUES ('id-proofs', 'id-proofs', true);
-- INSERT INTO storage.buckets (id, name, public) VALUES ('notice-images', 'notice-images', true);
-- INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true);
